# 389. Find the Difference

# You are given two strings s and t.
# String t is generated by random shuffling string s 
# and then add one more letter at a random position.

# Return the letter that was added to t.
def find_dif(s,t):
    
    list_s = list(s)
    list_t = list(t)
    for letra in list_s:
        if letra in list_t:
            list_t.remove(letra)
            
    if list_t:
        output = "".join(list_t)
        return output
    return False

# Example usage:
s = "abcde"
t = "abdedc"
result = find_dif(s,t)
print(result)